[package]
name = "cp-scheduler-credit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
sp-api = { version = "4.0.0-dev", default-features = false, git = 'https://github.com/CESSProject/substrate.git', branch = 'monthly-2022-04-cess' }
sp-core = { version = "6.0.0", default-features = false, git = 'https://github.com/CESSProject/substrate.git', branch = 'monthly-2022-04-cess' }
sp-std = { version = "4.0.0", default-features = false, git = 'https://github.com/CESSProject/substrate.git', branch = 'monthly-2022-04-cess' }
sp-application-crypto = { version = "6.0.0", default-features = false, git = 'https://github.com/CESSProject/substrate.git', branch = 'monthly-2022-04-cess' }
frame-support = {default-features = false, git = 'https://github.com/CESSProject/substrate.git', branch = 'monthly-2022-04-cess', version = '4.0.0-dev'}

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "sp-api/std",
    "sp-core/std",
    "sp-std/std",
    "sp-application-crypto/std",
	"frame-support/std",
]
