[package]
name = "pallet-tee-worker"
authors = ["CESS LAB"]
version = "0.7.6"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/CESSProject/cess"
description = "FRAME pallet for TEE Worker management"
readme = "README.md"

[dependencies]
log = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive", "max-encoded-len"] }
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
scale-info = { workspace = true, features = ['derive'] }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, features = ['alloc'] }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# local dependencies
cp-cess-common = { workspace = true }
cp-scheduler-credit = { workspace = true }
pallet-cess-staking = { workspace = true }
pallet-cess-pause = { workspace = true }
sgx-attestation = { workspace = true }
ces-types = { workspace = true, features = ["enable_serde"] }
ces-pallet-mq ={ workspace = true }


[dev-dependencies]
pallet-balances = { workspace = true }
pallet-timestamp = { workspace = true }
sp-staking = { workspace = true }
sp-npos-elections = { workspace = true }
frame-election-provider-support = { workspace = true }
pallet-session = { workspace = true }
pallet-bags-list = { workspace = true }
pallet-scheduler-credit = { workspace = true }
hex ={ workspace = true }

[features]
default = ["std"]
std = [
	"ces-types/enable_serde",
	"ces-pallet-mq/std",
	"codec/std",
	"chrono/std",
	"cp-cess-common/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-cess-staking/std",
	"pallet-session/std",
	"scale-info/std",
	"serde",
	"sgx-attestation/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
]
native = []
try-runtime = []