[package]
name = "ic-verify-bls-signature"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
description = "A library for handling BLS signatures"

[dependencies]
bls12_381 = { version = "0.7", default-features = false, features = ["groups", "pairings", "alloc", "experimental"] }
pairing = { version = "0.22", default-features = false }
lazy_static = { version = "1", default-features = false }
# rand = { version = "0.8.5", default-features = false, features = ["getrandom"] }

# Check references:
#  - https://docs.rs/getrandom/latest/getrandom/index.html
#  - https://rust-random.github.io/book/crates.html
# getrandom = { version = "0.2.10", default-features = false, features = ["js"] }
sha2 = { version = "0.9", default-features = false }
hex = { version = "0.4", default-features = false }
